services:
  frontend:
    image: nginx:latest
    container_name: tracks_frontend
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app_network

  api:
    build: ./backend
    container_name: tracks_api
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env.production
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - app_network

  mongo:
    image: mongo:6
    container_name: tracks_db
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tracks
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data: