GET http://localhost:5000/api/leaderboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODc1MzlkN2I2YWViM2QxOTc0NTY3M2MiLCJpYXQiOjE3NTI4NTQ2MjgsImV4cCI6MTc1Mjg1ODIyOH0.tuBVjSxTtTknlrrzF9mhUvBi9Oz-bD7mYt4E0GivyoI
Content-Type: application/json


###

#register user API
POST  http://localhost:5000/api/users/register
Content-Type: application/json

{
  "name": "Test11",
  "netId": "netBYU11",
  "username": "devUser11",
  "lab": "Doctor Evil Lab",
  "email": "test11@byu.test",
  "password": "12345678"
}


###
#user Login API
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test3@byu.test",
  "password": "12345678"
}

###
#update user profile API
PUT http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODc1MTJmOTliOWVkNDc2YTExYTQ4OWUiLCJpYXQiOjE3NTI1MTA3MDIsImV4cCI6MTc1MjUyNTEwMn0.XwGcd3-tmo1RW4UahVA7qEY4hF1jH0wALKXdhmkOSlQ
Content-Type: application/json


{
  "name": "Test1",
  "netId": "netBYU",
  "username": "devUser1",
  "lab": "Doctor Evil Lab",
  "email": "test1@byu.test",
  "password": "12345678"
}


###
#get user profiles API
GET http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODc1MzlhZDA1MWNlYzU4NWVkNGU5MjEiLCJpYXQiOjE3NTMyMjI4ODMsImV4cCI6MTc1MzIyNjQ4M30.xHBDPuRop4iFmDEponxD0MvEkRCUU081m2o1iKcZI98
Content-Type: application/json


###
#Log user logs
POST http://localhost:5000/api/logs/log
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODc1MzlhZDA1MWNlYzU4NWVkNGU5MjEiLCJpYXQiOjE3NTMyMjI4ODMsImV4cCI6MTc1MzIyNjQ4M30.xHBDPuRop4iFmDEponxD0MvEkRCUU081m2o1iKcZI98
Content-Type: application/json

{
  "date": "2025-07-12",
  "hours": 7.5,
  "description": "Worked on research World Domination 3."
}


###
#Delete user profiles API
DELETE  http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODc1M2JmN2I2YWViM2QxOTc0NTY3NWYiLCJpYXQiOjE3NTI1MTM3MDQsImV4cCI6MTc1MjUyODEwNH0._S5xa7TYPF1Uf3IG0IxD8vBO6cyGOwu1_t4GwSlszl0
Content-Type: application/json